apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: disco-bridge
  name: disco-bridge
  namespace: matrix
spec:
  ports:
  - name: disco-bridge
    port: 29334
    protocol: TCP
    targetPort: 29334
  selector:
    k8s-app: disco-bridge
  sessionAffinity: None
  type: ClusterIP
