apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gc-storage
  namespace: matrix
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
