apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wa-bridge
  name: wa-bridge
  namespace: matrix
spec:
  ports:
  - name: wa-bridge
    port: 29318
    protocol: TCP
    targetPort: 29318
  selector:
    k8s-app: wa-bridge
  sessionAffinity: None
  type: ClusterIP
