apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: secrets
  namespace: sops
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:8U+o9eu/qg==,iv:Peqm/DJVdjlRg5Z19woCN0lYLMnl2k+5anGVxSRFqno=,tag:a+PE1o2rbKu90QPJmjfYyQ==,type:str]
      stringData:
        key.txt: ENC[AES256_GCM,data:rEqPAAQHMWdQ7epKHR3e/XndskzHKCGCcGgHGn725IohAre6lCo0CyoX/z+JnIfZKN6O3YjA/Bkva57G63n3C9+E/g8oerPyoMak+pJdiolD6SZ/KVidVb24C/kPo5Ml7Di+2OKGw1JQZw9RsV5ubuVvvOls2CGf+gDPvWcQfQoyQgtX9ZOBRh8n7MCDRQ0QngNFgRO7yExmZtuhHoAlBpKhfXObIb8C0vfeiPSE1E6PRKTbNQW+aEaX2cP8,iv:xIg11/srkAfk3lTZDwjuF/U0fqwh2CvTJrr4cTSd6N4=,tag:YfjLAwsD5qkVPcUK9jzhtA==,type:str]
sops:
  age:
    - recipient: age1nkp9yxymndctx5e458xtqv87mk6fdv53vndejxys0ks2yju03c0qdvscg8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWXpzVWp4RWI1QkJ5SFl4
        Y2MxUXVEMmRURmdYYjEyUURqWEhrVTZoRjJBCkd6VjY2LzBuSnR5eTNMcTE3YzdV
        VU43b0dRd0kxM2FzeTBjVlVBT01vRTQKLS0tIGFLb0xPNEIxcFl5TFN0bzJCYks4
        Tm1qTHVoRHVxdEc3b3lKdzRJUWNVVWcKIqq4BM8mBQ606vrTNQpj8wuM/pD1hwSH
        VuwBhb4lnpd4kfesExNuoYkcU8T4sumhNNBRIDfIv8txKvOMagHYOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-05T18:44:28Z"
  mac: ENC[AES256_GCM,data:45aR4syCdmiqs3YAwxbt/BlPiYr6Ztbcma+AaRohS3Tx7gJ9Avfyrpv0P87SYnhoDVr21s2r+tNmRZrLNgU6ysb4NBMtp5TxqoSvdwfxeeFu96/MJ4Js1mw8x7yCK6qO+xMm7zmpcC2Ngqpn8WCsh0JG5NNUQDfZOPxy5myUB5M=,iv:QOJyTLtXyMOk9hxXKV2PNtK7BGtRKX0xqK5oukhwI6c=,tag:8rMxTJEifaRZYldeg5hoZg==,type:str]
  pgp:
    - created_at: "2026-07-05T18:45:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAz9aZqoHT9PNAQ//XPKz2+OREeM8u582pCwVExB8iKcHJEK1+UdmIuFL5vwf
        KoIhaox/lgozQMaTIF8AJvEjY1JfA2ExxbAG34Diq19r4SSrweZp+1NzM7BmZlDr
        M9C/qpsuBGQxkKTSTGbIFwyjp4cKBuL/ZgG3kdOgXmmMGAEz4X5icd4RWwx4QRZ0
        +pEUn6SOq9Yv5IyrsrXOvGDXmAtlcKS1kIww45W9kprOCjj9v5Cjl01Pzy8d/b7G
        qoy+WyYb7RHn0OPUrhpxynAl7kZxqMZ7h8jxK2hQzBx5LrzrO8KXr3P++ca3yXuB
        fHevkmgqjW8spfX3+/rBoGf2oChHRiyMg11iYlBdrZdIL4GutHFARfA5G50rQz8L
        c5Agseqo08biZa0IvAaIo2dC/O+NIE3CGNavuive2+9oDBOmQdrkkjbyAHP+RTmf
        wo2M2J452ly/pbdADuI6qz4a/Ts2Ib/8HadrSKgl7Mxo62ehJ5NTplx2S/dfSIN4
        osFcNlWwNwhs+s71f/SiEOJIcP+9S4VOiBSotEjkZEiC5jS/BpRiUJq3XM/h3uUA
        gCBevjABAMiPpuzV+l8StaBfxdOetW1CYftBE4XueyOdQ8f0ibUp2BUFSp41mszz
        mxokzZ5GxREUE+0zJL1qQoY95Cgwusu7EY+9MaXV29VuYoXIIBXOAWx77171nIvS
        XgHH3Krtf4XdAYaEXWlbGoIs0Pzk/McleAU+IES8NKWxxPtE9XxIq71CbmiayetO
        ZdHNLCAtMLMmuXzdJuR+3FvAUVcVTwGOEt8pTMM0yWzW8gR35u0nHgWSzbopNdY=
        =iR7m
        -----END PGP MESSAGE-----
      fp: 6528912C6687A3E2
  encrypted_suffix: Templates
  version: 3.11.0
