apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-storage
  namespace: matrix
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
