apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwdata
  namespace: bolcz
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
