# Create a service that makes the SSH service public on port 22
apiVersion: v1
kind: Service
metadata:
  name: containerssh
  namespace: bolcz
spec:
  selector:
    app: containerssh
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
  type: NodePort
