apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: secrets
  namespace: velero
spec:
  secretTemplates:
    - name: s3-ak-online-backups-creds
      stringData:
        cloud: ENC[AES256_GCM,data:7ReTGxIAkeonCOWiwXGdTUZM0mK5gqN6QFujGXONgBm4HumD+AKojatTWCgZuXA48aMfbtUS2EdbRti6w8awy5bzhStLSON5bTOeUKoe/eO7q7lCdqT1yocGm8CYUc+s1qiawIn12cDvjN4VC4RAiDzI,iv:CWqRv2mynW4ErXEMc/d1elShwHs1hYN4t8auv4geYdo=,tag:7RwlriqVdXU3rvm1BfYIgg==,type:str]
sops:
  age:
    - recipient: age1nkp9yxymndctx5e458xtqv87mk6fdv53vndejxys0ks2yju03c0qdvscg8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVnFkNGdNblZ2R0JBWUZx
        R1lGU1NSWWZ3MjQ3dlRzRlJMZGQzMG9XRFE0CjllS0ZOV2JXNmJDcGp3d2NGUGpi
        dmJWR1grQjE3Ym0wNDg0RHo0QjVNMWcKLS0tIGNueWttQ3ZNakMrKzhpM0JqN2FG
        Z00xajlTRFpGSlMxQlRBN3lDbFdKRWsKbYJ6ix/y7F5MeDa3L8jVgArAtMQSacl+
        P3fwZH3VcwpGXxaNgF/K34Rbe8UUJGfjhemgwDIO6as2C4WzBzT5YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:08:51Z"
  mac: ENC[AES256_GCM,data:s+8r1bag9DcN1hWLAKnu3KrxFD9xny58FdVNk5yHnp/XNFw/Q1rXbdYjFyqKC4v7XdXC7rSLxzlL7Lp6BPYz1NDm15gSwmpI9IoXRzoh7adykvMANGxBpQbAPlJnx6v94At4P9Glf/9Tx5ejECmOJ3JcfP/mNaKK40SMFSt7DgM=,iv:gE0Zul+YGnYPTNPcDGemam+7CvNahD6Dexgo1wIrduw=,tag:Z/BYDVuyupmg6vm7oqAB6w==,type:str]
  pgp:
    - created_at: "2025-12-07T22:08:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAz9aZqoHT9PNAQ/5AfpG45G5vOgYp+At7qtSUm4dOwWvOZ9pKZEn6/6414/8
        2Rr7WB7uiZFUaFKLb4xu//tvVQEOEwQWMogcrrtWeF1dbldwPTL2XsCeNGCm1u4Q
        MO4sYmgvNc8AL1lycZdIiW89SeFC04pDiymzkBGuq97sXek6L4EaLosS6hqLcfuI
        gWojtEhrbdOa0QNgSdPypH8WHdign3DahJ/qtqEnPHrac98g3Y/B+5AKRNH0JFOW
        /trxTssMZOvGJDSHm6oZ9TY5l/+8KVb10Ks5v44Qum4Tg3D/ReqcbX8pmqOfKKM8
        wBSOcMOnVHhne/LA3hRe+bO4/DIA3+cGonI17gH6+qDiu419hpAz/mO7P7xyWt5H
        Dtvpr4GpxHRY+a82k7TJtWs1UjOFlB7vFCzXWUTpvj50UqR+wZjgjrNOUxL3tnKI
        XOWDclZF8X8nYYQWSz1kloP2LCbK0UqVz3m7Vx5X/t2UUHsG+1NAOtaLjQ7AwMog
        6CWEhdtUVP8MRcAB8+g9H7ONc+gx3xj99v+M0WoU/j3XyGIeHcRw7svUH0K735WN
        VbeHHcWiISOUdHlmZa96AED+Q0tMZdbV3rLy/YPX1B+HzlFdTnaZGlxP3zHkp1Qg
        Z3VasixnSQIDaV4U9+Q4sk0FgJj5vbdkNBYzg5SehwpKQ/9vwyGfpou8wKjmtGzS
        XgHR1YpKvTqcO871Wn4NrI5H/8ZdnZiBIrCVPWumxoCn7n1xUnT7Da99FqCqx9Gu
        7lraeaSCZ1xY4MlKT49KElIb7ek8yAL+hR9BdOGZC4LXfH1TNegzyAc9YrKw5ns=
        =kD5s
        -----END PGP MESSAGE-----
      fp: 6528912C6687A3E2
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
