apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deploy-to-hosted
  namespace: hosted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-auto-deploy-to-hosted
  namespace: hosted
rules:
  - apiGroups:
    - "*"
    - "networking.k8s.io"
    - "apps"
    resources:
      - namespaces
      - deployments
      - deployment.apps
      - configmaps
      - pods
      - secrets
      - services
      - ingresses
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - patch
      - update
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-auto-deploy-to-hosted
  namespace: hosted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-auto-deploy-to-hosted
subjects:
  - kind: ServiceAccount
    name: github-deploy-to-hosted
    namespace: hosted
---
apiVersion: v1
kind: Secret
metadata:
  name: github-auto-deploy-token
  annotations:
    kubernetes.io/service-account.name: github-deploy-to-hosted
type: kubernetes.io/service-account-token
